module.exports.names = [
    "Luca",
    "Giulia",
    "Marco",
    "Francesca",
    "Matteo",
    "Chiara",
    "Andrea",
    "Elena",
    "Alessandro",
    "Sara",
    "Davide",
    "Valentina",
    "Federico",
    "Martina",
    "Simone",
    "Anna",
    "Gabriele",
    "Laura",
    "Riccardo",
    "Alessia",
    "Stefano",
    "Giorgia",
    "Leonardo",
    "Silvia",
    "Emanuele",
    "Beatrice",
    "Tommaso",
    "Alice",
    "Nicola",
    "Federica",
    "Lorenzo",
    "Ilaria",
    "Pietro",
    "Camilla",
    "Giovanni",
    "Claudia",
    "Filippo",
    "Bianca",
    "Antonio",
    "Veronica",
    "Michele",
    "Monica",
    "Francesco",
    "Sabrina",
    "Giuseppe",
    "Eleonora",
    "Alberto",
    "Rosa",
    "Enrico",
    "Caterina",
  ];
  
  module.exports.surnames = [
    "Rossi",
    "Bianchi",
    "Ferrari",
    "Esposito",
    "Russo",
    "Romano",
    "Colombo",
    "Ricci",
    "Marino",
    "Greco",
    "Bruno",
    "Gallo",
    "Conti",
    "De Luca",
    "Mancini",
    "Costa",
    "Giordano",
    "Rizzo",
    "Lombardi",
    "Moretti",
    "Barbieri",
    "Fontana",
    "Santoro",
    "Mariani",
    "Rinaldi",
    "Caruso",
    "Ferraro",
    "Fabbri",
    "Bianco",
    "Martini",
    "Leone",
    "Longo",
    "Gentile",
    "Sanna",
    "Sartori",
    "Monti",
    "Farina",
    "Ferrero",
    "Messina",
    "Donati",
    "Pellegrini",
    "Valentini",
    "Grassi",
    "Parisi",
    "Villa",
    "Piras",
    "Gatti",
    "Neri",
    "D'Amico",
    "Testa",
    "De Santis",
  ];
  
  module.exports.sexes = ["m", "f"];
  
  
  module.exports.sizesOptions = {
    tShirtSizes: ["xs", "s", "m", "l", "xl", "xxl"],
    trousersSizes: [38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
    shoeSizes: [36, 37, 28, 39, 40, 41, 42, 43, 44, 45, 46],
  };
  
  module.exports.types = ['top', 'trousers', 'shoes'];