name: Daily Birthday API Trigger

on:
  schedule:
    - cron: '30 7 * * *'  # 16:00 UTC = 18:30 Italy time (CEST)
  workflow_dispatch:       # Optional: lets you trigger manually

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Birthday API Endpoint
        run: |
          echo "Calling birthday API at $(date -u)"
          curl -s https://2mmshop-reg-clienti-production.up.railway.app/api/birthday
